# Generated by Django 5.2.12 on 2026-03-28 13:54

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='e.g., openai, anthropic, gemini', max_length=50, unique=True)),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
            ],
            options={
                'verbose_name': 'API Key Storage',
                'verbose_name_plural': 'API Key Storages',
            },
        ),
    ]
