# Generated by Django 5.2.12 on 2026-03-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('CONFIGURING', 'Configuring'), ('ABORTED', 'Aborted'), ('SUCCESS', 'Success')], default='READY', max_length=20),
        ),
        migrations.CreateModel(
            name='SessionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="AI provider key, e.g. 'openai', 'gemini', 'anthropic'", max_length=50)),
                ('archetype', models.CharField(choices=[('skeptic', 'Le Sceptique'), ('optimist', "L'Optimiste"), ('pragmatist', 'Le Pragmatique'), ('conservative', 'Le Conservateur'), ('innovator', "L'Innovateur")], help_text='Genetic Matrix archetype key', max_length=30)),
                ('slot_number', models.PositiveSmallIntegerField(help_text='Position 1-4 in the roundtable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='dashboard.session')),
            ],
            options={
                'verbose_name': 'Session Agent',
                'verbose_name_plural': 'Session Agents',
                'ordering': ['slot_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'slot_number'), name='unique_slot_per_session'), models.UniqueConstraint(fields=('session', 'archetype'), name='unique_archetype_per_session')],
            },
        ),
    ]
