# Generated by Django 5.2.12 on 2026-04-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_session_status_sessionagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('CONFIGURING', 'Configuring'), ('RUNNING', 'Running'), ('ABORTED', 'Aborted'), ('SUCCESS', 'Success')], default='READY', max_length=20),
        ),
    ]
