# Generated by Django 5.2.12 on 2026-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='abort_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
