# Generated by Django 5.2.12 on 2026-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_session_abort_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='discussion_axes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='moderator_model',
            field=models.CharField(default='gemini-3-flash-preview', max_length=120),
        ),
        migrations.AddField(
            model_name='session',
            name='moderator_provider',
            field=models.CharField(default='gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sessionagent',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text="Provider model id, e.g. 'gpt-5.5' or 'gemini-3-pro-preview'", max_length=120),
        ),
    ]
